core/blogger/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path("", views.home),
    path("list/", views.blog_list),
    path("create/", views.create_blog),
    path("myblogs/", views.myblogs),
    path("read/<id>/", views.read_blog),
    path("update/<id>/", views.update_blog),
    path("del/<id>/", views.delete_blog_get),
    path("del_confirm/<id>/", views.delete_confirm),
    path("read_myblog/<id>/", views.read_myblog)
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('blogger.urls')),
    path("auth/", include("userauth.urls")),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=staticfiles_urlpatterns()
    

core/userauth/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('register/', views.register),
    path('login/', views.login_page),
    path('logout/', views.logout_page),
]

core/blogger/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class blogs(models.Model):
    blog_text=models.TextField()
    blog_title=models.CharField(max_length=500)
    blog_image=models.ImageField(upload_to='blogimg', null=True, blank=True)
    created_at=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)

core/userauth/models.py
from django.db import models

# Create your models here.

core/blogger/views.py
from django.shortcuts import render,HttpResponse, redirect
from .models import blogs
from django.contrib import messages

# Create your views here.
def home(request):
    return HttpResponse("working ass expected")

def blog_list(request):
    blog_list=blogs.objects.all()
    return render(request,"bloglist.html", {"blogs":blog_list})

def create_blog(request):
    if request.method=="POST":
        try:
            img=request.FILES["blog_image"]
        except Exception as e:
            print(e)
            img=None
        data={"blog_text":request.POST['blog_content'], "blog_title":request.POST['blog_title'],"blog_image":img,"user":request.user}
        blogs.objects.create(**data)
        return redirect("/myblogs/")

    return render(request, "blogcreate.html")

def read_blog(request, id):    
    return render(request, "read.html",{"blog":blogs.objects.get(id=id)})

def update_blog(request, id):
    data=blogs.objects.get(id=id)
    if request.method=="POST":
        try:
            img=request.FILES['blog_image']
        except Exception as e:
            print(e)
            img=None
    
        data.blog_text=request.POST['blog_content']
        data.blog_title=request.POST['blog_title']
        if img:
            data.blog_image=img
        data.save()
        messages.info(request, "Blog has been updated Successfully!")
        return redirect("/myblogs/")
    return render(request,"blogupdate.html", {"blog":data})

def delete_confirm(request, id):
    data=blogs.objects.get(id=id)
    messages.error(request,f'''The blog "{data.blog_title}" has been deleted!''')
    data.delete()
    return redirect("/myblogs/")

def read_myblog(request,id):
    if request.method=='POST':
        pass
    return render(request, "user_read.html", {"blog":blogs.objects.get(id=id)})

def delete_blog_get(request, id):
    data=blogs.objects.get(id=id)
    return render(request, "deleteblog.html",{"blog":data})
def myblogs(request):
    return render(request, "myblogs.html", {"blogs":blogs.objects.filter(user=request.user)})

core/userauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def register(request):
    if request.method=='POST':
        check=User.objects.filter(username=request.POST['username'])
        if check.exists():
            messages.error(request, f'''The username "{request.POST['username']}" has already been taken.''')
            return redirect('/auth/register/')
        data={"username":request.POST['username'], "email":request.POST['email']}
        print(data)
        user=User(**data)
        user.set_password(request.POST['password'])
        user.save()
        messages.success(request, "Your account has been created successfully!")
        return redirect('/auth/login/')
    if request.user.is_authenticated:
        return redirect("/list/")
    return render(request,"register.html")

def login_page(request):
    if request.method=='POST':
        username=request.POST["username"]
        password=request.POST["password"]
        if not User.objects.filter(username=username).exists():
            messages.warning(request, "Invalid Credentials!")
            return redirect('/auth/login/')
        user=authenticate(username=username, password=password)
        if user==None:
            messages.warning(request, "Invalid Credentials!")
            return redirect('/auth/login/')
        login(request, user)
        messages.success(request,f'''Welcome back {user.username}''')
        return redirect("/list/")
    if request.user.is_authenticated:
        return redirect("/list/")
    return render(request,"login.html")

def logout_page(request):
    logout(request)
    messages.info(request, "You have been logged out!")
    return redirect('/auth/login/')

core/blogger/templates/base.html
<html>
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="" />
    <link
      rel="stylesheet"
      as="style"
      onload="this.rel='stylesheet'"
      href="https://fonts.googleapis.com/css2?display=swap&amp;family=Noto+Sans%3Awght%40400%3B500%3B700%3B900&amp;family=Space+Grotesk%3Awght%40400%3B500%3B700"
    />

    <title>Stitch Design</title>
    <link rel="icon" type="image/x-icon" href="data:image/x-icon;base64," />

    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
  </head>
  <body>
    <div class="relative flex size-full min-h-screen flex-col bg-[#121516] dark group/design-root overflow-x-hidden" style='font-family: "Space Grotesk", "Noto Sans", sans-serif;'>
      <div class="layout-container flex h-full grow flex-col">
        <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-b-[#2c3135] px-10 py-3">
          <div class="flex items-center gap-4 text-white">
            <div class="size-4">
              <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 6H42L36 24L42 42H6L12 24L6 6Z" fill="currentColor"></path></svg>
            </div>
            <h2 class="text-white text-lg font-bold leading-tight tracking-[-0.015em]"><a href="/list/">Bloggr</a></h2>
          </div>
          <div class="flex flex-1 justify-end gap-8">
            <div class="flex items-center gap-9">
              <a class="text-white text-sm font-medium leading-normal" href="/list/">Home</a>
              {% if request.user.is_authenticated %}
              <a class="text-white text-sm font-medium leading-normal" href="/myblogs/">My Blogs</a>
              {% endif %}
            </div>
            <button
              class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#b2d1e5] text-[#121516] text-sm font-bold leading-normal tracking-[0.015em]"
            >
              <span class="truncate">{% if request.user.is_authenticated %}<a href="/create/">New Post</a>
                  {% else %}<a href="/auth/register/">Create Account</a>
                  {% endif %}
                </span>
            </button>
            {% if request.user.is_authenticated %}
            <button
                class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#2c3135] text-white text-sm font-bold leading-normal tracking-[0.015em]"
              >
                <span class="truncate">
                  <a href="/auth/logout">Logout
                  </a>
                  
                </span>
              </button>
              {% endif %}
            {% if request.user.is_authenticated %}
              <div
              class="bg-center bg-no-repeat aspect-square bg-cover rounded-full size-10"
              style='background-image: url("https://cdn.pixabay.com/photo/2023/02/18/11/00/icon-7797704_640.png");'
            ></div>
            {% endif %}
          </div>
        </header>
        <div id="alert-container" class="px-40 pt-5">
            {% if messages %}
                {% for message in messages %}
                    <div class="p-4 mb-4 rounded-lg flex items-center justify-between
                                {% if message.tags == 'success' %}bg-green-800 text-white
                                {% elif message.tags == 'error' %}bg-red-800 text-white
                                {% elif message.tags == 'info' %}bg-blue-800 text-white
                                {% else %}bg-gray-700 text-white{% endif %}">
                        <div>{{ message }}</div>
                        <span class="cursor-pointer font-bold text-xl leading-none ml-4" onclick="this.parentElement.style.display='none';">&times;</span>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% block content %} 
        {% endblock %}
      </div>
    </div>
  </body>
</html>

core/blogger/templates/blogcreate.html
{% extends "base.html" %}
{% block content %}
<div class="px-40 flex flex-1 justify-center py-5">
  <div class="layout-content-container flex flex-col w-[512px] max-w-[512px] py-5 max-w-[960px] flex-1">
    <div class="flex flex-wrap justify-between gap-3 p-4"><p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">Create New Blog Post</p></div>
    
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} 
      
      <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
        <label class="flex flex-col min-w-40 flex-1">
          <p class="text-white text-base font-medium leading-normal pb-2">Blog Title</p>
          <input
          name="blog_title"
          re
          id="id_blog_title"
          placeholder="Enter your blog title"
          class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] h-14 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
          value=""
          />
        </label>
      </div>
      
      <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
        <label class="flex flex-col min-w-40 flex-1">
          <p class="text-white text-base font-medium leading-normal pb-2">Blog Content</p>
          <textarea
          name="blog_content"
          id="id_blog_content"
          required
          placeholder="Write your blog post here"
          class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] min-h-36 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
          ></textarea>
        </label>
      </div>
      
      <div class="flex flex-col p-4">
        <div class="flex flex-col items-center gap-6 rounded-xl border-2 border-dashed border-[#3c4a53] px-6 py-14">
                    <div class="flex max-w-[480px] flex-col items-center gap-2">
                      <p class="text-white text-lg font-bold leading-tight tracking-[-0.015em] max-w-[480px] text-center">Upload Image</p>
                      <p class="text-white text-sm font-normal leading-normal max-w-[480px] text-center">Click or drag an image to upload</p>
                    </div>
                    <label for="id_blog_image" class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#293238] text-white text-sm font-bold leading-normal tracking-[0.015em]">
                        <span class="truncate">Upload Image</span>
                        <input
                          type="file"
                          name="blog_image"
                          id="id_blog_image"
                          class="hidden" 
                          accept="image/*" 
                        />
                    </label>
                  </div>
                </div>
                
                <div class="flex px-4 py-3 justify-end">
                  <button
                    type="submit"
                    class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#1993e5] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                  >
                    <span class="truncate">Post</span>
                  </button>
                </div>
            </form>
            </div>
        </div>
{% endblock %}

core/blogger/templates/bloglist.html
{% extends "base.html" %}
{% block content %}

        <div class="px-40 flex flex-1 justify-center py-5">
          <div class="layout-content-container flex flex-col max-w-[960px] flex-1">
            <div class="flex flex-wrap justify-between gap-3 p-4"><p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">Published Posts</p></div>
           
{% for blog in blogs %}
            <div class="p-4">
              <div class="flex items-stretch justify-between gap-4 rounded-xl">
                <div class="flex flex-[2_2_0px] flex-col gap-4">
                  <div class="flex flex-col gap-1">
                    <p class="text-white text-[24px] font-bold leading-tight min-w-6">{{blog.blog_title}}</p>
                    <p class="text-[#e2e6e8] text-sm font-normal leading-normal">By {{blog.user.username}} · Published on July 15, 2024</p>
                    <p class="text-[#a2adb3] text-sm font-medium leading-normal">{{ blog.blog_text|truncatewords:50 }}</p>
                  </div>
                  <button
                    class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-8 px-4 flex-row-reverse bg-[#2c3135] text-white text-sm font-medium leading-normal w-fit"
                  >
                    <span class="truncate"><a href="/read/{{blog.id}}/">Read More</a></span>
                  </button>
                </div>
                <div
                  class="w-full bg-center bg-no-repeat aspect-video bg-cover rounded-xl flex-1"
                  style='background-image: url("/media/{{blog.blog_image}}"); background-size:contain; background-position: center; background-repeat: no-repeat;'
                ></div>
              </div>
            </div>
{% endfor %}
          </div>
        </div>
    {% endblock %}

core/blogger/templates/blogupdate.html
{% extends "base.html" %}
{% block content %}
<div class="px-40 flex flex-1 justify-center py-5">
  <div class="layout-content-container flex flex-col w-[512px] max-w-[512px] py-5 max-w-[960px] flex-1">
    <div class="flex flex-wrap justify-between gap-3 p-4"><p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">Update your Blog</p></div>
    
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %} 
      
      <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
        <label class="flex flex-col min-w-40 flex-1">
          <p class="text-white text-base font-medium leading-normal pb-2">Blog Title</p>
          <input
          name="blog_title" {# Add a name attribute #}
          id="id_blog_title" {# Good practice to add an ID #}
          placeholder="Enter your blog title"
          class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] h-14 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
          value="{{blog.blog_title}}"
          />
        </label>
      </div>
      
      <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
        <label class="flex flex-col min-w-40 flex-1">
          <p class="text-white text-base font-medium leading-normal pb-2">Blog Content</p>
          <textarea
          name="blog_content" {# Add a name attribute #}
          id="id_blog_content" {# Good practice to add an ID #}
          placeholder="Write your blog post here"
          class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] min-h-36 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
          
          >{{blog.blog_text}}</textarea>
        </label>
      </div>
      
      <div class="flex flex-col p-4">
        <div class="flex flex-col items-center gap-6 rounded-xl border-2 border-dashed border-[#3c4a53] px-6 py-14">
                    <div class="flex max-w-[480px] flex-col items-center gap-2">
                      <p class="text-white text-lg font-bold leading-tight tracking-[-0.015em] max-w-[480px] text-center">Upload Image</p>
                      <p class="text-white text-sm font-normal leading-normal max-w-[480px] text-center">Click or drag an image to upload</p>
                    </div>
                    <label for="id_blog_image" class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#293238] text-white text-sm font-bold leading-normal tracking-[0.015em]">
                        <span class="truncate">Upload Image</span>
                        <input
                          type="file"
                          name="blog_image" 
                          id="id_blog_image" {# Link this ID to the label's for attribute #}
                          class="hidden" {# Hide the default file input #}
                          accept="image/*" {# Optional: restrict file types #}
                        />
                    </label>
                  </div>
                </div>
                
                <div class="flex px-4 py-3 justify-end">
                  <button
                    type="submit" 
                    class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#1993e5] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                  >
                    <span class="truncate">Save Changes</span>
                  </button>
                </div>
            </form>
            </div>
        </div>
{% endblock %}

core/blogger/templates/deleteblog.html
{% extends "base.html" %}
{% block content %}
<div class="relative flex size-full min-h-screen flex-col bg-[#111518] dark group/design-root overflow-x-hidden" style='font-family: "Space Grotesk", "Noto Sans", sans-serif;'>
      <div class="layout-container flex h-full grow flex-col">
        <div class="px-40 flex flex-1 justify-center py-5">
          <div class="layout-content-container flex flex-col w-[512px] max-w-[512px] py-5 max-w-[960px] flex-1">
            <h2 class="text-white tracking-light text-[28px] font-bold leading-tight px-4 text-center pb-3 pt-5">Are you sure you want to delete this blog?</h2>
            <div class="flex justify-center">
              <div class="flex flex-1 gap-3 flex-wrap px-4 py-3 max-w-[480px] justify-center">
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#293238] text-white text-sm font-bold leading-normal tracking-[0.015em] grow"
                >
                  <span class="truncate"><a href="/myblogs/">Cancel</a></span>
                </button>
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#1993e5] text-white text-sm font-bold leading-normal tracking-[0.015em] grow"
                >
                  <span class="truncate"><a href="/del_confirm/{{blog.id}}">Delete</a></span>
                </button>
              </div>
            </div>
            <div class="p-4">
              <div class="flex items-stretch justify-between gap-4 rounded-xl">
                <div class="flex flex-[2_2_0px] flex-col gap-4">
                  <div class="flex flex-col gap-1">
                    <p class="text-white text-[24px] font-bold leading-tight min-w-6">{{blog.blog_title}}</p>
                    <p class="text-[#e2e6e8] text-sm font-normal leading-normal">By {{blog.user.username}} · Published on July 15, 2024</p>
                    <p class="text-[#a2adb3] text-sm font-medium leading-normal">{{ blog.blog_text|truncatewords:100}}</p>
                  </div>
                </div>
                <div
                  class="w-full bg-center bg-no-repeat aspect-video bg-cover rounded-xl flex-1"
                  style='background-image: url("/media/{{blog.blog_image}}"); background-size:contain; background-position: center; background-repeat: no-repeat;'
                ></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

core/blogger/templates/myblogs.html
{% extends "base.html" %}
{% block content %}
<div class="px-40 flex flex-1 justify-center py-5">
    <div class="layout-content-container flex flex-col max-w-[960px] flex-1">
        <div class="flex flex-wrap justify-between gap-3 p-4"><p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">My Blogs</p></div>
        {% for blog in blogs %}
            <div class="p-4">
              <div class="flex items-stretch justify-between gap-4 rounded-xl">
                <div class="flex flex-[2_2_0px] flex-col gap-4">
                  <div class="flex flex-col gap-1">
                    <p class="text-white text-base font-bold leading-tight">{{blog.blog_title}}</p>
                    <p class="text-[#a2adb3] text-sm font-normal leading-normal">By {{blog.user.username}} · Published on {{blog.created_at}}</p>
                    <p class="text-[#a2adb3] text-sm font-medium leading-normal">{{ blog.blog_text|truncatewords:50 }}<div class="flex justify-stretch">
              <div class="flex flex-1 gap-3 flex-wrap px-4 py-3 justify-center">
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#2c3135] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                >
                  <span class="truncate"><a href="/update/{{blog.id}}/">Edit</a></span>
                </button>
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#2c3135] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                >
                  <span class="truncate"><a href="/del/{{blog.id}}">Delete</a></span>
                </button>
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#b2d1e5] text-[#121516] text-sm font-bold leading-normal tracking-[0.015em]"
                >
                  <span class="truncate"><a href="/read_myblog/{{blog.id}}">Read</a></span>
                </button>
              </div>
            </div></p>
                  </div>
                  
                </div>
                <div
                  class="w-full bg-center bg-no-repeat aspect-video bg-cover rounded-xl flex-1"
                  style='background-image: url("/media/{{blog.blog_image}}"); background-size:contain; background-position: center; background-repeat: no-repeat;'
                ></div>
              </div>
            </div>
{% endfor %}
          </div>
        </div>
{% endblock %}

core/blogger/templates/read.html
{% extends "base.html" %}
{% block content %}
<div class="px-40 flex flex-1 justify-center py-5">
    <div class="layout-content-container flex flex-col max-w-[960px] flex-1">
        <div class="p-4">
            <div class="flex justify-between items-center mb-2">
                <p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">
                    {{blog.blog_title}}
                </p>
                <button
                    class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-8 px-4 bg-[#2c3135] text-white text-sm font-medium leading-normal"
                >
                    <span class="truncate"><a href="\list\">Back</a></span>
                </button>
            </div>

            <p class="text-gray-400 text-sm font-normal leading-normal">
                    By {{ blog.user.username }}
                <span class="mx-1">|</span> 
                Published on: {{ blog.created_at|date:"M d, Y" }}
            </p>

        </div>
        <p class="text-white text-base font-normal leading-normal pb-3 pt-1 px-4">
            {{blog.blog_text}}
        </p>
    </div>
</div>
{% endblock %}

core/blogger/templates/user_read.html
{% extends "base.html" %}
{% block content %}
<div class="px-40 flex flex-1 justify-center py-5">
    <div class="layout-content-container flex flex-col max-w-[960px] flex-1">
        <div class="p-4">
            <div class="flex justify-between items-center mb-2">
                <p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">
                    {{blog.blog_title}}
                </p>
                <button
                    class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-8 px-4 bg-[#2c3135] text-white text-sm font-medium leading-normal"
                >
                    <span class="truncate"><a href="\myblogs\">Back</a></span>
                </button>
            </div>

            <p class="text-gray-400 text-sm font-normal leading-normal">
                    By {{ blog.user.username }}
                <span class="mx-1">|</span> 
                Published on: {{ blog.created_at|date:"M d, Y" }}
            </p>

        </div>
        <p class="text-white text-base font-normal leading-normal pb-3 pt-1 px-4">
            {{blog.blog_text}}
        </p>
        <div class="flex justify-stretch">
              <div class="flex flex-1 gap-3 flex-wrap px-4 py-3 justify-start">
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#2c3135] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                >
                  <span class="truncate">Edit</span>
                </button>
                <button
                  class="flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 bg-[#2c3135] text-white text-sm font-bold leading-normal tracking-[0.015em]"
                >
                  <span class="truncate"><a href="/del/{{blog.id}}">Delete</a></span>
                </button>
              </div>
    </div>
</div>
{% endblock %}

core/userauth/templates/login.html
{% extends "base.html" %}
{% block content %}
        <form method="post">{% csrf_token %}
        <div class="px-40 flex flex-1 justify-center py-5">
          <div class="layout-content-container flex flex-col w-[512px] max-w-[512px] py-5 max-w-[960px] flex-1">
            <div class="flex flex-wrap justify-between gap-3 p-4"><p class="text-white tracking-light text-[32px] font-bold leading-tight min-w-72">Login</p></div>
            <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
              <label class="flex flex-col min-w-40 flex-1">
                <p class="text-white text-base font-medium leading-normal pb-2">Username</p>
                <input name="username"
                  required
                  placeholder="Enter your username"
                  class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] h-14 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
                  value=""
                />
              </label>
            </div>
            <div class="flex max-w-[480px] flex-wrap items-end gap-4 px-4 py-3">
              <label class="flex flex-col min-w-40 flex-1">
                <p class="text-white text-base font-medium leading-normal pb-2">Password</p>
                <input name="password"
                  type="password"
                  required
                  placeholder="Enter your password"
                  class="form-input flex w-full min-w-0 flex-1 resize-none overflow-hidden rounded-xl text-white focus:outline-0 focus:ring-0 border border-[#3c4a53] bg-[#1c2226] focus:border-[#3c4a53] h-14 placeholder:text-[#9daeb8] p-[15px] text-base font-normal leading-normal"
                  value=""
                />
              </label>
            </div>
            <div class="flex px-4 py-3">
              <button type="submit"
                class="flex min-w-[84px] max-w-[450px] cursor-pointer items-center justify-center overflow-hidden rounded-full h-10 px-4 flex-1 bg-[#1993e5] text-white text-sm font-bold leading-normal tracking-[0.015em]"
              >
                <span class="truncate">Login</span>
              </button>
            </div>
            <p class="text-[#e2e6e8] text-sm font-normal leading-normal px-6 py-1">Dont have an account? <a href="/auth/register/" class="text-[#0096FF] px-1">Signup</a></p>
          </div>
        </div>
        </form>
{% endblock %}